### ISSUE TITLE
goals?

### ISSUE THREAD

**Issue by atomGit** [xi/xiMatrix#1]
very interesting - glad to see someone is picking this up

may i ask what your goals are - how much functionality do plan on restoring/adding?

**Comment by xi** [comment]
Thanks for the interest!

To be honest, I am not planning many more features. The features that are already there are sufficient to replace uMatrix for the way I have used it for years.

There are still some bugs I want to iron out though. I might also experiment a bit with the new "inline" row. I was surprised to see how many sites require unsafe scripts. And it bothers me that there is currently no way to review all saved rules.

My top priority right now is to keep the code clean and simple. I will not add features that compromise simplicity too much.

So yeah, that's my answer. Did you have something specific in mind? Are you currently missing important features?

**Comment by atomGit** [comment]
> Did you have something specific in mind? Are you currently missing important features?

i'm not actually using the extension yet, but i am watching development - off the top of my head however, i'd guess people are going to request splitting media into frames and images

i used uM for a very long time until it started to become stale while, at around the same time, better storage isolation was implemented in FF and so i switched uBO into advanced mode and dropped uM

what i *wish* would have happened is that Gorhill would've ported the uM grid to uBO, or never split uM to begin with

anyway, happy coding and thanks for your comment
