### ISSUE TITLE
Completely broken pages

### ISSUE THREAD

**Issue by k-l-o-n-d-i-k-e** [xi/xiMatrix#2]
I have recently installed xiMatrix and i can't use it properly. The only active addon i have is xiMatrix and whenever it's active the entire page becomes broken. I tried changing some of the settings but it did not work.

![broken-odin](https://user-images.githubusercontent.com/108140943/184456495-d38a7c82-b381-4944-8029-ad066fa2e76a.png)

This is what it looks like with xiMatrix disabled. 

![unbroken page](https://user-images.githubusercontent.com/108140943/184456520-060e990f-8613-44bb-ad2e-b1d9b268da74.png)

Right now i am on Firefox 103 with windows 10.

**Comment by atomGit** [comment]
did you test with a fresh profile?

**Comment by k-l-o-n-d-i-k-e** [comment]
It's the same. Default configuration on Firefox, i didn't change any settings on about:config nor in the GUI settings. 

Also, i tried this on a different PC. 

![image](https://user-images.githubusercontent.com/108140943/184464551-0ca5c33d-b88e-4ac5-b033-51bc23bf5e63.png)

**Comment by xi** [comment]
This is a feature, not a bug. In fact, this is basically the only feature of this extension. To quote from the README (also on the mozilla addon page):

> By default, all web requests as well as inline code are blocked. You can then define rules to allow only those requests you want. Definitely for advanced users.

I tested the pages from your examples and they work fine for me if I allow the relevant requests. Am I assuming correctly that you didn't do this?

So I think this is more an issue of setting the correct expectations. What exactly made you think that this extension would *not* break pages? What did you expect it would do instead?

**Comment by k-l-o-n-d-i-k-e** [comment]
I am fully aware that this extension was going to make the pages break. But i don't think it should be the default. But that's okay, I'll just close this issue.
